Add Service Permission in manifest
mProjection = mpm.getMediaProjection(resultCode, data);

위의 checkpoint에서 아래와 같은 오류 발생

java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

-> Android 10 이후 foreground service가 아니라면 위와 같은 오류 발생

-> Foreground Service 를 먼저 생성하고 -> Activity 에서는 권한을 획득하는 구조로 동작해야 함.

-> AndroidManifest.xml 에 Service 권한 추가